### ISSUE TITLE
Fails to backup comic

### ISSUE THREAD

**Issue by phunni** [Cortys/comic-backup#51]
I've just run the comixology bacup on four new books that I bought and three of them worked perfectly, but the third (https://www.comixology.co.uk/Deadpool-Draculas-Gauntlet/digital-comic/150715) consistently fails.  

Every time I try it seem to be working, albeit very slowly, and then offers me a download file of something like "a51ee388-7632-4d3b-8384-b7d653d3aec4".

This file then fails to download saying that it can't be found.  I've tried renaming the file, but, unsurprisingly, it makes no difference.

**Comment by Cortys** [comment]
Could it be related to the length of the comic, or do the other three have about the same amount of pages?

As a temporary workaround I'd suggest using the "single image" download mode (found under "Container format" in the options) and then zipping the images yourself.

**Comment by phunni** [comment]
Could be the length of the comic - it is much longer than anything else I've tried to download - 873 pages

**Comment by Cortys** [comment]
I see. Let me know if you find any short comic that fails as well.

**Comment by phunni** [comment]
Will do - goodness, that was a fairly painful experience - 873 ages!  Still, it seems to have worked at least and it is now done.

**Comment by phunni** [comment]
I now have a comic (Gwenpool, The Unbelievable Vol. 1) which is failing after about 88 pages.  Again, a slightly shorter one (the Gwenpool holiday special) is succeeding, but I wouldn't have thought 88 pages was long - although the scan says it's at about 56% when it fails.  It also fails in the same way with Vol . 2.

Additionally it fails when using Single Page Download... Eventually the page with the scan always fails with the "Aw, Snap" error.

**Comment by Cortys** [comment]
Thanks for the report, I'm looking into it.

Does this happen for every comic of that length or just the ones you mentioned?

**Comment by phunni** [comment]
I've tried one a little longer (200 pages as opposed to 158 in the ones mentioned above) and it failed again.  I'm struggling to find one a similar length.

I may well be barking up the wrong tree, but I'm wondering if it's something to do with storage.  Where does the extension store temporary files?  I've tried changing the tmp dir for Chrome, but it doesn't actually seem possible.

**Comment by cecoates** [comment]
I don't know if we're having exactly the same issue, but when I find the same comic failing over and over (and usually at the same place), I wait about a day, try it again, and I'm able to download it.

Maybe they don't like it if you seem to be hammering their servers? Although you'd think they have cloud storage for days.

**Comment by Cortys** [comment]
Closing this, as there are duplicate issues for the problems described here.
* UUID filenames: #52 
* Missing pages: #64
