### ISSUE TITLE
Request: Specify Download Folder

### ISSUE THREAD

**Issue by AndrewD2** [Cortys/comic-backup#58]
I have a script setup that scans a specific folder for my comics. Would it be possible to get an option that allows you to set the download folder as something over than the default chrome download folder? For me I used %USER%/Download/Comics. It's not a big deal but it would be nice to have to find each folder and move it before a scan is done.

Thank you.

**Comment by Cortys** [comment]
Unfortunately Chrome only extensions to download files to the downloads folder and subdirectories.

One option to solve your problem could be to allow setting the name of a target directory **inside** of Chrome's downloads folder (which could be watched by your script).

Would that help? If yes, I'll add this in the next release. Of course a PR is also welcome.

**Comment by AndrewD2** [comment]
Setting a folder name inside the default directory would work perfectly. Alas my knowledge of the Chrome extension API and JS are rather limited at this time or I would do a PR.

**Comment by Cortys** [comment]
Fixed via #71. Sorry that took so long.
