### ISSUE TITLE
Scanning Fails

### ISSUE THREAD

**Issue by perrinaz** [Cortys/comic-backup#62]
The comic I would like to backup doesn't appear to have a single page method so it always fails after the "click on dual page mode" test.  The comic link is: https://www.comixology.com/Weekly-Shonen-Jump-Vol-246-10-31-2016/

**Comment by Cortys** [comment]
Hi! The setup steps have to be performed only once. To start using the extension, you initially have to choose a comic with single page support. After that you can backup dual page comics as well.

Hopefully this solves your problem. Please let me know if it doesn't.

**Comment by perrinaz** [comment]
I actually found that after I posted my issue in the "closed" issues.  You might want to put something about this in the README for those of us who come looking for something to save manga.

**Comment by Cortys** [comment]
Glad you could solve the issue.

And you are right. Communicating this more clearly probably is a good idea.
