### ISSUE TITLE
leaves out pages when copied and pasted to different hard drive

### ISSUE THREAD

**Issue by Andrepartthree** [Cortys/comic-backup#66]
Hi there , first I wanted to say thank you SO much for writing this program !  :) .. it's really nice to be able to take full ownership of  the comics I paid good money for !  :P 

I have however run into a little problem  :(   ... the add-on to comixology works fine as long as I keep the downloaded comic anywhere on the C drive where comixology is installed... however I like to keep my documents on a separate  drive within my computer , frees up space on my SSD hard drive (which is the C drive) and if I have to reinstall Windows 8 on the C drive that way I don't lose all my documents too  :) .. the documents are stored on a SATA hard drive.

Whenever I try to copy and paste the downloaded comic from my C drive to a different drive (for example the " E " drive  letter that has been assigned to my SATA hard drive or my USB thumb drive I use for backups) , it doesn't copy and paste the complete comic... it'll leave out a random number of pages towards the very end of the comic.... 

Thanks so much for reading this and again I know I speak for all of us when I say I really appreciate you creating this program !  :)

**Comment by Andrepartthree** [comment]
Well edit and update.... stupid me, I was leaving my comic book reader (comic rack) open when I was copying and pasting.... exiting out of it BEFORE copying and pasting is what I should be doing, kind of tricky because when you exit out of the comic you just assume you automatically exit out of comic book reader too but apparently not  :P  ... 

However, I did find that it's leaving out pages after the download from the comic, randomly it appears (like pages are missing in the middle of the comic, at the end, and so forth) .... 

Not sure what I'm doing wrong  "P   - is there a particular comic book reader that is more favorably disposed towards reading the comic book downloads perhaps? :)

**Comment by Cortys** [comment]
This sounds more like an issue with the extension, not your reader.

Could you try using the [latest development version](https://github.com/Cortys/comic-backup/archive/master.zip)?

This should help. There have been multiple issues regarding missing pages recently due to changes in Chrome and the Comixology Reader. I have not yet found the time to properly address them all yet, but the current state solves most of them.

You should probably check all your backups for completeness, just to be safe. Checking the page count is usually sufficient.

**Comment by Andrepartthree** [comment]
Thank you SO much this worked beautifully !  All set now !  :)

**Comment by Cortys** [comment]
Yes, Germany is correct. Didn't know PayPal wants to know that.Thanks for your support! Am 21.06.2017 6:28 vorm. schrieb Andrepartthree <notifications@github.com>:Thank you SO much this worked beautifully !  All set now !  :)
