### ISSUE TITLE
Generated filenames of zips are UUIDs

### ISSUE THREAD

**Issue by sgbeal** [Cortys/comic-backup#68]
Not a big deal, just somewhat annoying when backing up many books: the generated download/CBZ files are named UUIDs, with no extension. e.g.:

663034da-0237-4c44-8893-a8622f2709c8

instead of Whatever.cbz. It happens 100% of the time.

This has been happening for 6+ months, in various versions of Chrome on Linux, currently:

Version 63.0.3239.108 (Official Build) (64-bit)

git says i'm using the current (as of this moment) version of comic-backup.

PS: thanks a million for maintaining this app. It's let me back up well over 1500 books over the past couple of years.

**Comment by sgbeal** [comment]
i don't know if this is related or normal: i am using the "save each page into its own file" option for the for the first time, and it's storing each page as a UUID.png. i was expecting them to be named page##.png, like the generated CBZs do. This is not a huge problem, because 'ls' has an option to sort them by their timestamps, which can be used to rename them, but it's somewhat unexpected. (Though it may, i'll admit, be necessary when backing up multiple books, as they all go into the same directory.)

**Comment by bzfoster** [comment]
Make sure you don't have a download manager enabled. I'm using the Free Download Manager extension in Chrome and I get names exactly like what you are experiencing  when that extension is enabled. When I disable it, the names are correct.

**Comment by sgbeal** [comment]
Aha - that may well be the problem. i have the Chrono manager installed. Let me try this...

... waiting ... (i throttle the backup to avoid looking too suspicious to comixology access log analyzers :/ ...
42%...

that...

75%...

was the problem.

Thank you!
