### ISSUE TITLE
Failed - Network error

### ISSUE THREAD

**Issue by perrinaz** [Cortys/comic-backup#79]
The extension walks each page but when it tries to save the page the download tab shows "Failed - Network Error" and the extension page shows the error:  

Uncaught TypeError: onend is not a function
Context
_generated_background_page.html

Platform: Windows 10, latest Chrome (72), Saving as individual image files, not a zip or cbz.  Extension was successfully used two weeks ago.

**Comment by sgbeal** [comment]
i'm guessing here, but is your Chrome-configured Download directory on a network drive? If you're doing this at work, it might be a network drive without you realizing it, depending on how your office's machines are administered.

**Comment by perrinaz** [comment]
No, I am saving it all to my D: drive which is a partition of my only hard drive.

**Comment by perrinaz** [comment]
Self Resolved
