### ISSUE TITLE
(Mac OS 10.14.3) (Chrome 72) Specified Download Folder Crashes Download

### ISSUE THREAD

**Issue by MightyAx** [Cortys/comic-backup#80]
### Issue
When using a Specified download folder of ~/Comics/ the progress would halt at "Saving" and never complete.
### Failed Resolution Attempt
Tried giving the **Everyone** user group **Read & Write** access to ~/Comics/ rather than just my own user. This had no effect.
### Workaround
Clearing the specified download folder so that the tool used the default chrome download folder fixed the issue.

**Comment by sgbeal** [comment]
i'm guessing here, but did you enter a literal tilde `~/... ` for the path? If so, not all software can deal with that properly - try using the absolute path to that directory. That's just a guess, though.

**Comment by Cortys** [comment]
Problem tracked in #86.
