### ISSUE TITLE
Stuck at "Saving" / "Saving comic..."

### ISSUE THREAD

**Issue by vic000047** [Cortys/comic-backup#87]
I'm on macOS Mojave and everything worked perfectly so far, but when the script or the extension to save the comic, it just stays there forever... :( Any solution?
![Screenshot 2020-05-20 at 11 25 03](https://user-images.githubusercontent.com/65651644/82423568-98549380-9a8c-11ea-89df-3a096fe5b09b.png)
![Screenshot 2020-05-20 at 11 25 12](https://user-images.githubusercontent.com/65651644/82423575-9b4f8400-9a8c-11ea-87d4-660dc73b8398.png)

**Comment by TBthegr81** [comment]
It will be saying "Saving" and then open a File-Download windows in your browser where yar supposed to choose where to save the file. When that popup have either been canceled or ok'ed "Saving" status is removed

Especially if ya where doing other stuff, letting it download in the background ya might not notice the download-modal, check all the windows belonging to yar browser.

**Comment by vic000047** [comment]
I did everything you said. Nothing appears or changes... I'll let it sit like that for one hour, but it wont do anything :( ...no popup ever comes. Checked every tab and everything. Not even a sign of a dwonload pending...it's just frozen.
I just tried on Windows 10 as well, with no luck.
I'm trying to get for myself the Scooby-Doo comics from https://www.comixology.com/

**Comment by TBthegr81** [comment]
If ya open developers console does it say anything?
(F12 on some machines, or right-click and "inspect", or Chrome menu -> More Tools -> Developer Tools)

**Comment by TBthegr81** [comment]
Also, if yar looking at the tab it opens when it prepares the download, does it successfully reach the end of the comic and thus should be able to save the stuff? If for some reason it gets stuck in the comic-reader that might be another issue.

**Comment by vic000047** [comment]
Yea, it does get to the end. And on the last page of the comics it tries to save the download...but it just not doing it.

**Comment by vic000047** [comment]
Also, I found those two errors or whatever they are, under the extensions panel...hmmm...what are those?!

![Screenshot 2020-05-20 at 12 34 10](https://user-images.githubusercontent.com/65651644/82430658-4dd81480-9a96-11ea-911c-e35dc7208730.png)
![Uploading Screenshot 2020-05-20 at 12.34.15.png…]()

**Comment by vic000047** [comment]
Well nevermind. I got it to work perfectly by getting the 2.3.3 version...lol. Weird but, oki. Sorry for the trouble. :)
