### ISSUE TITLE
Special character issue

### ISSUE THREAD

**Issue by mastressalita** [Cortys/comic-backup#89]
I've run into the same problem I experienced before ( read here: https://github.com/Cortys/comic-backup/issues/88 ) where one of my comics goes through the "scan" process but doesn't create a folder with the downloaded files in it. Before, it was a tilde in the name of the comic that caused an issue with creating the download directory. This comic has an ellipses (title: ...and I Love You) and I'm experiencing the same problem -- I see the files "scanning" but have no directory with files on my computer after it is done.

Thanks for any help with this issue!

**Comment by zbrasseaux** [comment]
What OS are you on? some systems mark files that start with a period as hidden files.

**Comment by mastressalita** [comment]
I'm on Windows 7, 64bit, and my Folder Options are already set to "Show Hidden Files, Folders, and Drives"

**Comment by Cortys** [comment]
Thanks for the report! Should be fixed in the new 2.4.1 release.
